#!/bin/sh 
sudo raspi-config nonint do_i2c 0
sudo raspi-config nonint do_rgpio 0

sudo raspi-config nonint do_spi 0
sudo systemctl enable pigpiod


pathLocale=$(readlink -f .)

chmod +x scriptStarter
python -m venv .venv
. venv/bin/activate
.venv/bin/python3 setup.py


pathLocale=$(readlink -f .)

printf "#!/bin/sh 
sleep 3
cd %s
.venv/bin/python3 "home.py" 
exit 0" $pathLocale > scriptStarter

printf "[Unit]
Description=magnetism Service
After=multi-user.target
Requires=network.target
[Service]
Type=idle
ExecStart=/usr/bin/sudo %s/scriptStarter
Restart=always
RestartSec=10
[Install]
WantedBy=multi-user.target" $pathLocale > /etc/systemd/system/myService.service
chmod 644 /etc/systemd/system/myService.service
systemctl daemon-reload
systemctl enable myService.service
read -p "Reboot needed , do you want to restart now? [y,n]" doit 
case $doit in  
  y|Y) reboot;;  
  *) printf "\nreboot rinviato\n" ;; 
esac